CREATE DATABASE DocflowApplicationDB;
GO

CREATE LOGIN FlowUser WITH PASSWORD = 'CHANGE_ME_STRONG_PASSWORD';
GO

USE DocflowApplicationDB;
GO

CREATE USER FlowUser FOR LOGIN FlowUser;
ALTER ROLE db_owner ADD MEMBER FlowUser;
GO
