# Generated by Django 5.2.4 on 2026-06-02 09:37

import django.db.models.deletion
import django.utils.timezone
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('route_type', models.CharField(choices=[('sequential', 'Последовательный'), ('parallel', 'Параллельный')], default='sequential', max_length=20, verbose_name='Тип маршрута')),
                ('is_default', models.BooleanField(default=False, verbose_name='Маршрут по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Маршрут согласования',
                'verbose_name_plural': 'Маршруты согласования',
                'ordering': ['document_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Код для номера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('default_due_days', models.PositiveSmallIntegerField(default=3, verbose_name='Срок согласования, дней')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=150, verbose_name='Этап')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('due_days', models.PositiveSmallIntegerField(default=3, verbose_name='Срок, дней')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='documents.approvalroute', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Этап согласования',
                'verbose_name_plural': 'Этапы согласования',
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=250, verbose_name='Тема')),
                ('system_number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Системный номер')),
                ('internal_number', models.CharField(blank=True, max_length=80, verbose_name='Внутренний номер компании')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('returned', 'Возвращен на доработку'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('in_progress', 'В работе'), ('completed', 'Исполнен'), ('archived', 'Архив')], default='draft', max_length=30, verbose_name='Статус')),
                ('registration_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата регистрации')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок исполнения/согласования')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма')),
                ('counterparty', models.CharField(blank=True, max_length=250, verbose_name='Контрагент')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Пользовательские поля')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.department', verbose_name='Подразделение')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_documents', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.approvalroute', verbose_name='Маршрут согласования')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
                'permissions': [('view_all_documents', 'Может видеть все документы'), ('soft_delete_document', 'Может помечать документы на удаление')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление/пометка'), ('view', 'Просмотр'), ('approve', 'Согласование'), ('reject', 'Отклонение'), ('return', 'Возврат'), ('delegate', 'Делегирование'), ('archive', 'Архивация')], max_length=30, verbose_name='Действие')),
                ('message', models.TextField(verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер, байт')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash файла')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('returned', 'Возвращено'), ('delegated', 'Делегировано')], default='pending', max_length=20, verbose_name='Статус')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Делегировано кому')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.approvalstep', verbose_name='Этап')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Задача согласования',
                'verbose_name_plural': 'Задачи согласования',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_routes', to='documents.documenttype', verbose_name='Тип документа'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.department', verbose_name='Подразделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=120, verbose_name='Название поля')),
                ('key', models.SlugField(max_length=80, verbose_name='Технический ключ')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Да/Нет'), ('choice', 'Список')], default='text', max_length=20, verbose_name='Тип поля')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('choices', models.TextField(blank=True, help_text="Один вариант на строку. Используется только для типа поля 'Список'.", verbose_name='Варианты для списка')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='documents.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Пользовательское поле',
                'verbose_name_plural': 'Пользовательские поля',
                'ordering': ['document_type__name', 'sort_order', 'name'],
                'unique_together': {('document_type', 'key')},
            },
        ),
    ]
