# Generated by Django 5.2.4 on 2026-06-03 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_contractkind_documentpurpose_userprofile_patronymic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Этап согласования')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('due_days', models.PositiveSmallIntegerField(default=3, verbose_name='Срок, дней')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configured_document_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_approvers', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Согласующий документа',
                'verbose_name_plural': 'Согласующие документа',
                'ordering': ['document', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='configured_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentapprover', verbose_name='Согласующий документа'),
        ),
    ]
