# Generated by Django 5.2.4 on 2026-06-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_revision_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('returned', 'На доработке'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('in_progress', 'В работе'), ('completed', 'Исполнен'), ('archived', 'Архив')], default='draft', max_length=30, verbose_name='Статус'),
        ),
    ]
