# Generated by Django 5.2.4 on 2026-07-08 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval_required', 'Требуется согласование'), ('status_changed', 'Изменение статуса'), ('comment_added', 'Добавлен комментарий'), ('password_reset', 'Сброс пароля')], max_length=40, verbose_name='Тип уведомления'),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('code', models.CharField(max_length=4, verbose_name='Код подтверждения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('used', 'Использован'), ('expired', 'Истек')], default='pending', max_length=20, verbose_name='Статус')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос сброса пароля',
                'verbose_name_plural': 'Запросы сброса пароля',
                'ordering': ['-created_at'],
            },
        ),
    ]
