# Generated by Django 5.2.4 on 2026-07-24 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Текст письма')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток отправки')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_delivery', to='documents.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Отправка email',
                'verbose_name_plural': 'Отправки email',
                'ordering': ['-created_at'],
            },
        ),
    ]
