# Generated by Django 5.2.4 on 2026-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_emaildelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='reminder_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок в напоминании'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напоминание отправлено'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval_required', 'Требуется согласование'), ('approval_reminder', 'Напоминание о согласовании'), ('status_changed', 'Изменение статуса'), ('comment_added', 'Добавлен комментарий'), ('password_reset', 'Сброс пароля')], max_length=40, verbose_name='Тип уведомления'),
        ),
    ]
