# Generated by Django 5.2.4 on 2026-08-13 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_route_types_and_versions(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    ApprovalTask = apps.get_model("documents", "ApprovalTask")

    Document.objects.filter(route__route_type="parallel").update(approval_route_type="parallel")
    tasks = list(ApprovalTask.objects.select_related("document").all())
    for task in tasks:
        task.document_version = task.document.version
    if tasks:
        ApprovalTask.objects.bulk_update(tasks, ["document_version"])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_approvaltask_reminder_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='document_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='approval_route_type',
            field=models.CharField(choices=[('sequential', 'Последовательный'), ('parallel', 'Параллельный')], default='sequential', max_length=20, verbose_name='Тип маршрута согласования'),
        ),
        migrations.RunPython(preserve_existing_route_types_and_versions, migrations.RunPython.noop),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('document_version', models.PositiveIntegerField(default=1, verbose_name='Версия с замечанием')),
                ('comment', models.TextField(verbose_name='Замечание')),
                ('status', models.CharField(choices=[('open', 'Требует исправления'), ('resolved', 'Исправлено')], default='open', max_length=20, verbose_name='Статус')),
                ('resolution_comment', models.TextField(blank=True, verbose_name='Внесенные корректировки')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата исправления')),
                ('resolved_in_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Исправлено в версии')),
                ('approval_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_request', to='documents.approvaltask', verbose_name='Задача согласования')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='documents.document', verbose_name='Документ')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_revision_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто вернул на доработку')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_document_revision_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто внес корректировки')),
            ],
            options={
                'verbose_name': 'Замечание по документу',
                'verbose_name_plural': 'Замечания по документам',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
