# Generated by Django 5.2.4 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_correspondence_historical_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="document_version",
            field=models.PositiveIntegerField(default=1, verbose_name="Версия документа"),
        ),
        migrations.AddField(
            model_name="revisionrequest",
            name="resolution_attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_revision_requests",
                to="documents.attachment",
                verbose_name="Файл с исправлениями",
            ),
        ),
    ]
